// import "../../public/bootstrap/css/bootstrap.min.css";
import "bootstrap/dist/css/bootstrap.min.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div id="" className="container-xxl">
          {children}
        </div>
        <script src="/bootstrap/js/bootstrap.bundle.js"></script>
      </body>
    </html>
  );
}
